
(defvar *opt-settings* '(optimize (safety 1) (speed 3) (debug 3)))

; use this to hide compiler notes:
;(declaim (sb-ext:muffle-conditions sb-ext:compiler-note))

(load "~/quicklisp/setup.lisp")

(asdf:defsystem "weir"
  :description "A System for Making Generative Systems"
  :version "3.73.1"
  :author "anders hoff/inconvergent"
  :licence "MIT"
  :serial t
  :depends-on ("zpng" "cl-svg" "png" "alexandria" "cl-json" "lparallel"
               "inferior-shell")
  :components ((:file "various")
               (:file "packages")
               (:file "fn")
               (:file "state")
               (:file "math/math")
               (:file "rnd/rnd")
               (:file "vec/base")
               (:file "vec/vec")
               (:file "vec/3vec")
               (:file "vec/avec")
               (:file "parallel/main")
               (:file "math/curvature")
               (:file "project/perspective")
               (:file "project/ortho")
               (:file "project/raytrace")
               (:file "draw/cpath")
               (:file "math/path")
               (:file "math/simplify-path")
               (:file "draw/hatch")
               (:file "draw/line-remove")
               (:file "pigment/pigment")
               (:file "pigment/non-alpha")
               (:file "pigment/extra")
               (:file "hset")
               (:file "rnd/extra")
               (:file "rnd/walkers")
               (:file "rnd/3rnd")
               (:file "graph/main")
               (:file "graph/paths")
               (:file "graph/edge-set")
               (:file "graph/mst-cycle")
               (:file "aux/dat")
               (:file "gridfont/main")
               (:file "draw/bzspl")
               (:file "draw/lin-path")
               (:file "draw/sandpaint")
               (:file "draw/sandpaint-extra")
               (:file "draw/draw-svg")
               (:file "distance/zonemap")
               (:file "distance/kdtree")
               (:file "distance/bvh-utils")
               (:file "mesh/mesh")
               (:file "mesh/vert-utils")
               (:file "mesh/shapes")
               (:file "mesh/lights")
               (:file "mesh/obj")
               (:file "mesh/bvh")
               (:file "mesh/line")
               (:file "mesh/raytracer")
               (:file "mesh/raytracer-refract")
               (:file "point-cloud/main")
               (:file "point-cloud/bvh")
               (:file "point-cloud/raytracer")
               (:file "weir/weir")
               (:file "weir/vert-utils")
               (:file "weir/planar-cycles")
               (:file "weir/cycles")
               (:file "weir/3vert-utils")
               (:file "weir/alterations")
               (:file "weir/3alterations")))

(setf *random-state* (make-random-state t))
(setf *print-pretty* t)

